[build-system]
requires = ["setuptools", "wheel", "radvel", "numpy"]
build-backend = "setuptools.build_meta"


[project]
dynamic = ["version"]
name = 'scarvs'
authors = [
    {name = 'Neil Cook', email = 'neil.james.cook@gmail.com'},
]
description = 'Statistical tools for Combined Analysis of Radial Velocity Signals'
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = 'LICENSE'}
requires-python = "==3.11.*"
dependencies = [
    "juliet==2.2.7",
    "arviz==0.20.0",
    "astropy==7.0.1",
    "batman-package==2.5.2",
    "corner==2.2.3",
    "dynesty==2.1.5",
    "emcee==3.1.6",
    "ipython==9.0.0",
    "jax==0.4.31",
    "jaxoplanet==0.0.3",
    "kepmodel==1.0.8",
    "lightkurve==2.5.0",
    "matplotlib==3.10.1",
    "notebook==7.3.2",
    "numba==0.61.0",
    "numexpr==2.10.2",
    "numpy==1.26.4",
    "numpyro==0.17.0",
    "pandas==2.2.3",
    "pandastable==0.13.1",
    "ruamel.yaml==0.18.10",
    "scipy==1.15.2",
    "spleaf==2.1.13",
    "starry==1.2.0",
    "tinygp==0.3.0",
    "tqdm==4.67.1",
    "wget==3.2",
    "xarray==2025.1.2"
]

[project.urls]
Homepage = 'http://apero.exoplanets.ca'
Repository = 'https://github.com/njcuk9999/scarvs'

[project.scripts]
scarvs_setup = "scarvs:recipes.scarvs_setup.run"
scarvs_run = "scarvs:recipes.scarvs_run.run"

[project.optional-dependencies]
full = ["aperocore @ git+https://github.com/njcuk9999/apero-drs.git@v0.8.003#subdirectory=apero-core"]
dev = ["aperocore"]